# Generated by Django 5.2.6 on 2025-09-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_status_alter_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='rental_days',
            field=models.IntegerField(blank=True, help_text='Nombre de jours de location', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='rental_end_date',
            field=models.DateField(blank=True, help_text='Date de fin de location', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='rental_start_date',
            field=models.DateField(blank=True, help_text='Date de début de location', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='total_rental_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coût total de la location', max_digits=10, null=True),
        ),
    ]
