# Generated by Django 5.2.6 on 2025-09-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_id_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='daily_rental_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix de location par jour', max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='is_available_for_rent',
            field=models.BooleanField(default=True, help_text='Disponible pour la location'),
        ),
    ]
